### PR TITLE
Update: Default tile colours for both Mazes

### PR DESCRIPTION
**Pull request by Zebiano**
This PR sets the default tiles for the Dismal and Arcane Labyrinth. It also sets the "Zeb version" by default, yet people are of course still able to change to dark mode, etc.

### CODE REVIEW

**Comment by kevingrillet** [comment]
[Here ](https://github.com/Zebiano/AFKArena-LabHelper/blob/wip/js/script-words.js#L75)you need to replace:
-  `case 'zeb':` with `case 'game':`

And [here ](https://github.com/Zebiano/AFKArena-LabHelper/blob/wip/js/script-color.js#L61-L64) you need to replace:
- `case 'zeb':` with `case 'light':` 
- `case 'light':` with `case 'dark':`

Yes, my cookie management is garbage 😉

**Review by kevingrillet — CHANGES_REQUESTED** [review]
https://github.com/kevingrillet/AFKArena-LabHelper/pull/25#issuecomment-1057703577

**Comment by Zebiano** [comment]
I ran both `npm run pretty` and `npm run lint`, but please make sure linting rules are being followed in this PR.

**Review by kevingrillet — APPROVED** [review]

**Comment by kevingrillet** [comment]
> I ran both `npm run pretty` and `npm run lint`, but please make sure linting rules are being followed in this PR.

I just put random values in both 😄 
I'm not an expert with prettier and lint

**Pull request merged**
